### ISSUE TITLE
changeVersion not supported

### ISSUE THREAD

**Issue by qmatteoq** [MSOpenTech/cordova-plugin-websql#17]
Is there any plan to add support to the changeVersion() method to set the version number of the schema?
Right now, calling code like db.changeVersion("1", "2") returns the following error:

0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'changeVersion'

Thanks!

**Comment by sgrebnov** [comment]
@qmatteoq Thank you for reporting this, I'll investigate this and reply w/ details tomorrow.

**Comment by johnshepherd** [comment]
Hi is there any update on this? This is pretty crucial functionality wise for an app we're building.

**Comment by sgrebnov** [comment]
Implementation for Windows https://github.com/MSOpenTech/cordova-plugin-websql/commit/17015eb938d902eeb6018c03e438658103b28c17

**Comment by darinez** [comment]
@sgrebnov Is there any plan to add support to the changeVersion() method to WP8?

Thanks!

**Comment by sgrebnov** [comment]
Hey @darinez discussing w/ my team if we have capacity for this...

**Comment by darinez** [comment]
Thanks for answering! I hope so.
