### ISSUE TITLE
Database does not open on Windows@3.8.1

### ISSUE THREAD

**Issue by fidransky** [MSOpenTech/cordova-plugin-websql#25]
I am developing an app using this plugin for some time now but after updating the Cordova CLI, the windows platform and the plugin to their last versions recently, the application stopped working - the database does not even open. 
I am getting this JS console log: 

```
device ready
openDatabase: name = jasenverkko
[Database] name: jasenverkko, lastTransactionId: 0. | new Database(); name = jasenverkko
[Database] name: jasenverkko, lastTransactionId: 0. | Database.open() err = {"description":"'SQLite' is undefined","number":-2146823279,"stack":"ReferenceError: 'SQLite' is undefined\n   at module.exports.getVersion (ms-appx://cz.pavelfidransky.bachelor/www/plugins/cordova-plugin-websql/src/windows/WebSqlProxy.js:23:13)\n   at module.exports (ms-appx://cz.pavelfidransky.bachelor/www/cordova.js:890:13)\n   at callback (ms-appx://cz.pavelfidransky.bachelor/www/plugins/cordova-plugin-websql/www/windows/Database.js:50:9)\n   at cordova.callbackFromNative (ms-appx://cz.pavelfidransky.bachelor/www/cordova.js:288:41)\n   at cordova.callbackSuccess (ms-appx://cz.pavelfidransky.bachelor/www/cordova.js:268:9)\n   at onSuccess (ms-appx://cz.pavelfidransky.bachelor/www/cordova.js:867:17)\n   at module.exports.open (ms-appx://cz.pavelfidransky.bachelor/www/plugins/cordova-plugin-websql/src/windows/WebSqlProxy.js:66:13)\n   at module.exports (ms-appx://cz.pavelfidransky.bachelor/www/cordova.js:890:13)\n   at Database (ms-a
[Database] name: jasenverkko, lastTransactionId: 0. | transaction
[Database] name: jasenverkko, lastTransactionId: 1. | transaction
database created
[SqlTransaction] id: 2, connectionId: undefined. | executeSql, ERROR: Connection is not set
[Database] name: jasenverkko, lastTransactionId: 2. | transaction.run callback error, lastTransactionId = 2; error: Error: Connection is not set
[SqlTransaction] id: 2, connectionId: undefined. | executeSql, ERROR: Connection is not set
SCRIPT5022: Unhandled exception at line 27, column 9 in ms-appx://cz.pavelfidransky.bachelor/www/plugins/cordova-plugin-websql/www/windows/SqlTransaction.js
0x800a139e - JavaScript runtime error: Connection is not set
File: SqlTransaction.js, Line: 27, Column: 9
```

It all worked well until the update. I haven't changed a single line of code: the database is opened after `deviceready` and all variables are set correctly. 
I also tried to completely remove the plugin and the platform and add them back but it didn't help.

Tools and their versions used: 
Cordova CLI: 5.0.0 
Windows platform: 3.8.1 
WebSQL plugin: 0.0.8 
Visual Studio Express 2013
Windows 8.1 Pro

If there are any other information I need to supply, feel free to ask me.

**Comment by daserge** [comment]
Hi @fidransky,

Does the issue reproduce on Windows Phone 8.1 project only?

The fix is related to SQLite.Proxy reference missing in Windows Phone 8.1 project and it is not yet published to npm.

To test whether it helps please reinstall the plugin from github this way:
```cordova plugin rm cordova-plugin-websql```
```cordova plugin add https://github.com/MSOpenTech/cordova-plugin-websql```

**Comment by fidransky** [comment]
Hi,
I removed the plugin and added it from GitHub and now I can't build the app at all. It gives me a nice colorful error log in the command line:

```
C:\Users\Pavel\Documents\bachelor>cordova build windows -- --phone
Running command: C:\Users\Pavel\Documents\bachelor\platforms\windows\cordova\bui
ld.bat --phone
Applying Platform Config...
MSBuildToolsPath: C:\Program Files (x86)\MSBuild\12.0\bin\amd64\
Building project: C:\Users\Pavel\Documents\bachelor\platforms\windows\CordovaApp
.Phone.jsproj
        Configuration : debug
        Platform      : anycpu

C:\Program Files (x86)\MSBuild\12.0\bin\amd64\Microsoft.Common.CurrentVersion.t
argets(991,5): warning MSB3644: The reference assemblies for framework ".NETCor
e,Version=v4.5" were not found. To resolve this, install the SDK or Targeting P
ack for this framework version or retarget your application to a version of the
 framework for which you have the SDK or Targeting Pack installed. Note that as
semblies will be resolved from the Global Assembly Cache (GAC) and will be used
 in place of reference assemblies. Therefore your assembly may not be correctly
 targeted for the framework you intend. [C:\Users\Pavel\Documents\bachelor\plug
ins\cordova-plugin-websql\src\windows\SQLite.Proxy\SQLite.Proxy\SQLite.Proxy.cs
proj]

CSC : error CS0518: Predefined type 'System.Object' is not defined or imported
[C:\Users\Pavel\Documents\bachelor\plugins\cordova-plugin-websql\src\windows\SQ
Lite.Proxy\SQLite.Proxy\SQLite.Proxy.csproj]

ERROR: Error code 1 for command: C:\Program Files (x86)\MSBuild\12.0\bin\amd64\m
sbuild with args: C:\Users\Pavel\Documents\bachelor\platforms\windows\CordovaApp
.Phone.jsproj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:
Configuration=debug,/p:Platform=anycpu,/p:BuildFromCordovaTooling=true

ERROR building one of the platforms: Error: C:\Users\Pavel\Documents\bachelor\pl
atforms\windows\cordova\build.bat: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: C:\Users\Pavel\Documents\bachelor\platforms\windows\cordova\build.bat: Co
mmand failed with exit code 2
    at ChildProcess.whenDone (C:\Users\Pavel\AppData\Roaming\npm\node_modules\co
rdova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

Note that I tried to build using both `cordova build windows` and `cordova build windows -- --phone` commands with the same result.
.NET v4.5 is mentioned to be missing in the log but I'm pretty sure I have it installed.

**Comment by daserge** [comment]
@fidransky,

Can you please check if the [sample app](https://github.com/MSOpenTech/cordova-plugin-websql/issues/19#issuecomment-91268812) works for you?

Can you also try to build from Visual Studio?

**Comment by fidransky** [comment]
Build from Visual Studio failed too with this error:

```
Could not copy the file "C:\Users\Pavel\Documents\bachelor\plugins\cordova-plugin-websql\src\windows\SQLite.Proxy\SQLite.Proxy\bin\Debug\SQLite.Proxy.winmd" because it was not found.
```

I will take a look at the sample app later.

**Comment by daserge** [comment]
@fidransky,
Can you please try to remove post-build events from SQLite.Proxy project?
To do it make a right click on SQLite.Proxy project in Visual Studio > Build events > clear `Post-build event command line` field.

**Comment by fidransky** [comment]
I didn't need to. When you pointed me to the SQLite.Proxy project, I noticed that it was targetted on Windows 8.0. After I retargetted the project, Visual Studio was able to build the app and it started to work.

Running build from Cordova CLI is also successful with this warning only:

```
C:\Program Files (x86)\MSBuild\12.0\bin\amd64\Microsoft.Common.CurrentVersion.t
argets(1940,6): warning MSB3851: This project targets "Windows, Version=8.0", b
ut it is attempting to reference "C:\Users\Pavel\Documents\bachelor\plugins\cor
dova-plugin-websql\src\windows\SQLite.Proxy\SQLite.Proxy\bin\Debug\SQLite.Proxy
.winmd" targeting "Windows,Version=8.1", which is invalid. [C:\Users\Pavel\Docu
ments\bachelor\platforms\windows\CordovaApp.Windows80.jsproj]
```

**Comment by darinez** [comment]
I tried to build my app from Visual Studio 2015 CTP 6 with this plugin (version": "0.0.9") and I had the same problem:

Unhandled exception at line 27, column 9 in XXX/www/plugins/cordova-plugin websql/www/windows/SqlTransaction.js

0x800a139e - JavaScript runtime error: Connection is not set

I'm waiting for your answer

Thanks!

**Comment by fidransky** [comment]
@darinez,
I was faster :-) Try to retarget the SQLite.Proxy project in Visual Studio.

**Comment by daserge** [comment]
Hi @darinez,

Can you please try to use the fixed version?
```
git clone -b packaging-cleanup https://github.com/msopentech/cordova-plugin-websql
cd app-folder-name
cordova plugin rm cordova-plugin-websql
cordova plugin add ..\cordova-plugin-websql
```

**Comment by darinez** [comment]
@fidransky @daserge 

Finally I reinstall version of plugin from github and retarget SQLite.Proxy project to Windows 8.1 and it works for me.

Thanks to both!

**Comment by fidransky** [comment]
Great, thank you @daserge

**Comment by daserge** [comment]
@fidransky, @darinez 
Glad to help, guys

This issue should be fixed now with [this PR](https://github.com/MSOpenTech/cordova-plugin-websql/pull/27) and I believe that retarget should not be required.

Please let us know if you encounter any issues with the plugin.

**Comment by pelikhan** [comment]
Has the cordova repository been updated? Does it mean that we always need to install from the github repo from now on?

**Comment by fidransky** [comment]
Hopefully not for ever but yes, I did it so.

**Comment by nsteenbeek** [comment]
@pelikhan I had same "Connection is not set" issue and installing from the github repo solved the problem. I had this problem with Windows Phone.
