### ISSUE TITLE
too many projects in solution

### ISSUE THREAD

**Issue by yechongbo** [MSOpenTech/cordova-plugin-websql#28]
Hi,

I am using Visual Studio for cordova, after upgrading websql plugin to 0.0.9, it reports an error which is 'too many projects in solution'. How can i cope with this? thanks!

**Comment by deividkamui** [comment]
Same issue here

**Comment by daserge** [comment]
Hi guys,
The issue is caused by old Cordova version in VS 2013 MDA tools and is fixed in VS 2015 - could you please verify this?
(VS 2013.4 MDA uses Cordova 4.1.2 and [the fix](https://github.com/apache/cordova-lib/commit/623233d099d7874be134fe4a9e0b645a7426eb57) has been released with 4.2.0.)

**Comment by yechongbo** [comment]
verified, thanks!
