### ISSUE TITLE
SQLite not defined

### ISSUE THREAD

**Issue by Dbaprateek** [MSOpenTech/cordova-plugin-websql#29]
I am using cordova 3.8.0 with VS2013 
<div class="app">
            <h1>Apache Cordova</h1>
            <div id="deviceready" class="blink">
                <p class="event listening">Connecting to Device</p>
                <p class="event received">Device is Ready</p>
            </div>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript">
            document.addEventListener('deviceready', onDeviceReady, false);
            function onDeviceReady() {
                window.__webSqlDebugModeOn = true;
                var db = openDatabase('test1.db', '1.0', 'testLongTransaction', 2 * 1024);
                db.transaction(function (tx1) {
                    tx1.executeSql('DROP TABLE IF EXISTS foo');
                    tx1.executeSql('CREATE TABLE IF NOT EXISTS foo (id unique, text)');
                    db.transaction(function (tx2) {
                        tx2.executeSql('INSERT INTO foo (id, text) VALUES (1, "foobar")');
                    }, null, null, null, null, false, tx1);
                }, null, null);
            }
        </script>

**Comment by Dbaprateek** [comment]
[Database] name: test1.db, lastTransactionId: 0. | Database.open() err = {"description":"'SQLite' is undefined","number":-2146823279,"stack":"ReferenceError: 'SQLite' is undefined\n   at module.exports.getVersion (ms-appx://io.cordova.hellocordova/www/plugins/com.msopentech.websql/src/windows/WebSqlProxy.js:23:13)\n   at module.exports (ms-appx://io.cordova.hellocordova/www/cordova.js:874:13)\n   at callback (ms-appx://io.cordova.hellocordova/www/plugins/com.msopentech.websql/www/windows/Database.js:50:9)\n   at cordova.callbackFromNative (ms-appx://io.cordova.hellocordova/www/cordova.js:286:41)\n   at cordova.callbackSuccess (ms-appx://io.cordova.hellocordova/www/cordova.js:266:9)\n   at onSuccess (ms-appx://io.cordova.hellocordova/www/cordova.js:858:17)\n   at module.exports.open (ms-appx://io.cordova.hellocordova/www/plugins/com.msopentech.websql/src/windows/WebSqlProxy.js:66:13)\n   at module.exports (ms-appx://io.cordova.hellocordova/www/cordova.js:874:13)\n   at Database (ms-appx://io.cordova.hellocordo

**Comment by Dbaprateek** [comment]
Please Help

**Comment by kirreal** [comment]
Same issue

**Comment by front-a-little** [comment]
Any news on this issue ? Installed and updated this plugin from this git repo, retargeted SQLite.Proxy project to Win8.1
Breaks in WebSqlProxy.js at line 106
````var res = SQLite.Proxy.SQLiteProxy.connectToDb(module.exports.db);````
claiming 
> SQLite is undefined

Other global objects this script relies on, like require, module or Windows, are available

**Comment by front-a-little** [comment]
I managed to fix this issue by adding SQLite.Proxy to the References list of my Cordova project:
In Visual Studio, rightclick you project (not the solution)
Select "Add" > "Reference...", the Reference Manager should show up
On the left hand site, select "Solution" if it's not active already
You should see SQLite.Proxy in that list, simply tick the checkbox and confirm your changes.
Gave me a warning but built the project and after this, SQLite wasn't undefined anymore

**Comment by TrygveSkogsholm** [comment]
I am getting 'this' bug in VS 2015 RTM.

Exception was thrown at line 23, column 13 in ms-appx://.../www/plugins/com.msopentech.websql/src/windows/WebSqlProxy.js
 - JavaScript runtime error: 'SQLite' is undefined

I don't have a Proxy project to retarget, visual studio claimed to install it all via GUI interface to the config.xml.

**Comment by iandonov** [comment]
Same here:
[Database] name: DBname, lastTransactionId: 0. | new Database(); name = DBname
[Database] name: DBname, lastTransactionId: 0. | Database.open() err = {"description":"'SQLite' is undefined","number":-2146823279,"stack":"ReferenceError: 'SQLite' is undefined
   at module.exports.getVersion (ms-appx://AppName/www/plugins/cordova-plugin-websql/src/windows/WebSqlProxy.js:23:13)
   at module.exports (ms-appx://AppName/www/cordova.js:901:13)
   at callback (ms-appx://AppName/www/plugins/cordova-plugin-websql/www/windows/Database.js:50:9)
   at cordova.callbackFromNative (ms-appx://AppName/www/cordova.js:291:41)
   at cordova.callbackSuccess (ms-appx://AppName/www/cordova.js:271:9)
   at onSuccess (ms-appx://AppName/www/cordova.js:874:17)
   at module.exports.open (ms-appx://AppName/www/plugins/cordova-plugin-websql/src/windows/WebSqlProxy.js:66:13)
   at module.exports (ms-appx://AppName/www/cordova.js:901:13)
   at Database (ms-appx://AppName/www/plugi
db successfully opened or created  -----?!?

**Comment by cmitel** [comment]
I have the same issue for WP8.1 execution and I am using Cordova-cli 5.1.1.

This error comes from the plugin.xml definition for `windows` platform within the `framework` element :
```
<platform name="windows">
        <js-module src="www/WebSQL.js" name="WebSQL">
            <merges target="window" />
        </js-module>
        <js-module src="www/windows/Database.js" name="Database" />
        <js-module src="www/windows/SqlTransaction.js" name="SqlTransaction" />

        <framework src="src/windows/SQLite.Proxy/SQLite.Proxy/SQLite.Proxy.csproj"
            custom="true" type="projectReference" target="windows" />

        <js-module src="src/windows/WebSqlProxy.js" name="WebSqlProxy">
            <runs />
        </js-module>
    </platform>
```
The attribute `target`should have the value **all** and not `windows`, because the project referenced isn't loaded for the phone build which is causing  the `SQLite Undefined` error.

After this change, I did the following command : `cordova platform rm windows && cordova platform add windows && cordova build windows` and this works for me.

**Comment by daserge** [comment]
Hi guys,
Is this issue still reproducing on the latest github version?
If yes, please state your VS and cordova versions.

**Comment by tomchiverton** [comment]
Yes. Visual Studio 2015 community, fresh install (so whatever versions of cordova Microsoft are shipping now).
Added from the core plugins list, but doesn't appear to do anything, attempting to use window.openDatabase throws a not defined error.

**Comment by cmitel** [comment]
@tomchiverton can you show us the content of ```plugin.xml``` file downloaded to your project please ? Only the part concerning ```windows```.

**Comment by tomchiverton** [comment]
My project is trying to use Windows Universal on a locally attached device (a Lumia with Windows 8.1).

My ..../BlankCordovaApp1/BlankCordovaApp1/plugins/cordova-plugin-websql/plugin.xml has this as well as other <platform> nodes.
```
    <platform name="windows">
        <js-module src="www/WebSQL.js" name="WebSQL">
            <merges target="window" />
        </js-module>
        <js-module src="www/windows/Database.js" name="Database" />
        <js-module src="www/windows/SqlTransaction.js" name="SqlTransaction" />

        <framework src="src/windows/SQLite.Proxy/SQLite.Proxy/SQLite.Proxy.csproj"
            custom="true" type="projectReference" target="windows" />

        <js-module src="src/windows/WebSqlProxy.js" name="WebSqlProxy">
            <runs />
        </js-module>
    </platform>

```

**Comment by daserge** [comment]
@tomchiverton could you please try to update 
```xml
<framework src="src/windows/SQLite.Proxy/SQLite.Proxy/SQLite.Proxy.csproj"
            custom="true" type="projectReference" target="windows" />
```

to
```xml
<framework src="src/windows/SQLite.Proxy/SQLite.Proxy/SQLite.Proxy.csproj"
            custom="true" type="projectReference" target="all"/>
```

Looks like the VS takes the old version from `npm`.

**Comment by tomchiverton** [comment]
Tried that already. Should I have to do anything special to trigger a rebuild ?

Also is adding via the right click menu on config.xml all that is required ? i.e. no .js file to include ?

**Comment by daserge** [comment]
@tomchiverton could you please try to move the project to the drive where you have Temporary folder (usually `c:`), and then try to add the plugin using Git link (in VS config.xml -> Plugins -> Custom -> Git): 
`https://github.com/MSOpenTech/cordova-plugin-websql`?

**Comment by tomchiverton** [comment]
Removed the existing plugin, added a new one from the custom git link, and launched debug again.

window.openDatabase still not defined

**Comment by tomchiverton** [comment]
My bad I think. I wasn't including platformOverides.js

**Comment by daserge** [comment]
Does it work now?
The plugin itself should work without `winstore-js-compat`, which is enabled by platform overrides.

**Comment by tomchiverton** [comment]
Yes. 
-- 
Tom

**Comment by tomchiverton** [comment]
(that's, "yes, from Git". Broken from Visual Studio's main list, as described here

**Comment by daserge** [comment]
0.0.10 version has been published to npm, the plugin now should work from VS 2015 core plugins list.
Please reopen in case of issues.
