### ISSUE TITLE
Not able to Delete Records

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [MSOpenTech/cordova-plugin-websql#32]
Hi , I am new to apache cordova and am trying to do a simple ToDo app as given in the samples. I am able to insert and read the records from the database but the records are not getting deleted. I have used it in a similar way as shown in the sample.

When I use the Ripple Emulator in Google Chrome in Visual Studio 2015 it works as expected but when I deploy to an android device (Nexus 4) it is not working. Just the delete functionality is not working.

The Delete All :
db.transaction(function (tx) {
        alert('In Delete All');
        tx.executeSql("DELETE FROM todo", null, onSuccess, onError);
    });

Please help me resolve this incase I have missed any of the settings or used it wrongly.

**Comment by daserge** [comment]
Hi @VigneshVaidyanathan,
Looks like the issue reason is [this line](https://github.com/MSOpenTech/cordova-plugin-websql/blob/519b8a5bbcc46d2ef820fcae94b43cdf3d98dd2e/test/js/index.js#L20) in `onSuccess` callback:
```javascript
document.getElementById("lblTxInfo").innerHTML = 'RowsAffected: ' + resultSet.rowsAffected + '; InsertId: ' + resultSet.insertId;
```

[WebSQL spec](http://www.w3.org/TR/webdatabase/#database-query-results):
`
The insertId attribute must return the row ID of the row that the SQLResultSet object's SQL statement inserted into the database, if the statement inserted a row. If the statement inserted multiple rows, the ID of the last row must be the one returned. If the statement did not insert a row, then the attribute must instead raise an INVALID_ACCESS_ERR exception.
`

So `resultSet.insertId` getter throws on Android in DELETE success handler.
You can wrap accessing insertId in try/catch block as a workaround.
