### ISSUE TITLE
crash if restarted quickly

### ISSUE THREAD

**Issue by tomchiverton** [MSOpenTech/cordova-plugin-websql#38]
I'm still working on small test case, but in our app if the app is closed and immediately reopened then it crashes almost immediately.
f you wait at least 10 seconds then it works as expected.
The DB is very small (half dozen tables, hardly any data).

If I comment the openDatabase() then this doesn't occur.
Crashes never occur when connected to the Visual Studio debugger.

is there an easy way to capture the crash?

**Comment by daserge** [comment]
@tomchiverton, regarding capturing the crash - you can go to `EventViewer` (`Control Panel` -> `View event logs`), click `View` -> `Show Analytic and Debug Logs`, expand `Applications and Services Logs` -> `Microsoft` -> `Windows` -> `AppHost`.
Admin logs will contain crash events there and you can also enable `AppTracing` logs to see IE console output.
The latter option can be combined with 
```javascript
window.__webSqlDebugModeOn = true;
```
If you are using Cordova CLI, you can achieve the similar via running
```
.\platforms\windows\cordova\log
```
as Administrator and then running your app.
