### ISSUE TITLE
Plugin Does Not Work in Windows 10

### ISSUE THREAD

**Issue by marcos-queiroz** [MSOpenTech/cordova-plugin-websql#50]
I'm studying Cordova, and recently I was testing the project on WIndows 10, but storing using WebSQL did not work.

So I researched and found this Plugin, but when running on Windows10 it does not work.

I noticed that the documentation says support for Windows 8 and 8.1.

I would like to know when we will support Windows 10 Universal Platform.

Thank you for your attention.

**Comment by daserge** [comment]
@marcos-queiroz which error are you getting - could you please add some details and reproduce steps?

**Comment by daserge** [comment]
So in terms of the sample/test app situated in `pluginRoot/test` you would need to remove `MSApp.execUnsafeLocalFunction` usage as it's no more required in a Windows 10 app and specify a build architecture (x64 or x86 for desktop or ARM for phone) as AnyCPU is not supported for Windows 10 builds.

**Comment by marcos-queiroz** [comment]
@daserge thank you very much, I was not taking care of the architecture issue, I changed it to x64 and it worked perfectly.

**Comment by daserge** [comment]
Great, thanks for confirmation! Please close the issue if this is resolved.
